---
services:
  sound-provider-youtube:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sound-provider-youtube
    restart: unless-stopped
    ports:
      - "4002:3000"
    networks:
      - app

networks:
  app:
    driver: bridge