services:
  sound-provider-youtube:
    image: ghcr.io/jimce-music/sound-provider-youtube:latest
    container_name: sound-provider-youtube
    restart: unless-stopped
    ports:
      - "4002:4002"
    volumes:
      - ./media:/app/media
    networks:
      - app
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4002/info"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  app:
    driver: bridge
