---
services:
  sound-provider-youtube:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sound-provider-youtube
    restart: unless-stopped
    ports:
      - "4002:4002"
    volumes:
      - ./media:/app/media
    networks:
      - app

networks:
  app:
    driver: bridge